import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Ambio",
  description: "Generated by create next app",
  icons: {
    icon: "/insta.svg", // Favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preloading images */}
        <link rel="preload" href="/Untitled_design__2_-removebg.png" as="image" />
        <link rel="preload" href="/Untitled_design__3_-removebg-preview.png" as="image" />
        <link rel="preload" href="/Untitled_design__4_-removebg-preview.png" as="image" />
        <link rel="preload" href="/Untitled_design__5_-removebg-preview.png" as="image" />
      </head>
      <body className="bg-gradient-to-r from-gray-800 to-black">
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-PL78QCCX08"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-PL78QCCX08');
          `}
        </Script>
        {children}
      </body>
    </html>
  );
}
