import type { Metadata } from "next";
import "./globals.css";

import Head from "next/head";

export const metadata: Metadata = {
  title: "Ambio",
  description: "Generated by create next app",
  icons: {
    icon: "/insta.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Preloading images */}
        <link rel="preload" href="/Untitled_design__2_-removebg.png" as="image" />
        <link rel="preload" href="/Untitled_design__3_-removebg-preview.png" as="image" />
        <link rel="preload" href="/Untitled_design__4_-removebg-preview.png" as="image" />
        <link rel="preload" href="/Untitled_design__5_-removebg-preview.png" as="image" />
        
        {/* Favicon */}
      </Head>
      <body className="bg-gradient-to-r from-gray-800 to-black">
        {children}
      </body>
    </html>
  );
}
